### ISSUE TITLE
Non beta release?

### ISSUE THREAD

**Issue by derekprior** [Voog/wysihtml-rails#2]
Any chance you could release a gem version tied to the latest non-beta release?

**Comment by gomayonqui** [comment]
:+1: trying to use this gem in a engine, but can't require a gem pre released version. Any chance you could release a version?

**Comment by tanelj** [comment]
Hi!

@derekprior - the last non beta release was published under different gem name https://rubygems.org/gems/wysihtml5x-rails (before rebranding), but it's quite out of date. Actually the latest release is quit stable and there has lot of improvements (e. g.  MS Edge support, added by version `beta14` : https://github.com/Voog/wysihtml/releases/tag/0.5.0-beta14)

@gomayonqui - can you specify your problem? Actually it should not to be problem to include pre-released gems in engine. Here is more about bundler syntax: http://bundler.io/gemfile.html: Exmple:

You can either require specific version in your engine gemspec file:

```
s.add_dependency 'wysihtml-rails', '~> 0.5.0.beta14'
```

or relaxed latest beta pre-released version:

```
s.add_dependency 'wysihtml-rails', '~> 0.5.0.beta'
```

**Comment by tanelj** [comment]
Hi!

I'm happy to announce that new stable version 0.5.0 has been released now: https://github.com/Voog/wysihtml-rails/releases
